<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PhimSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('phims')->delete();
        DB::table('phims')->insert([
            [
                'ten_phim'          => 'The Conjuring: Ma Xui Quỷ Khiến',
                'slug_phim'         => 'the-conjuring-ma-xui-quy-khien',
                'id_the_loai'       => 1,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/vi/4/4c/The_Conjuring_3_VN_poster.jpg',
                'dao_dien'          => 'James Wan',
                'dien_vien'         => 'Vera Farmiga, Patrick Wilson, Ruairi O Connor',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '112',
                'mo_ta'             => 'The Conjuring: Ma Xui Quỷ Khiến là phần thứ 3 trong series phim kinh dị The Conjuring. Phim kể về một vụ án ma ám kinh hoàng xảy ra tại một ngôi nhà ở Connecticut, Mỹ vào năm 1981.',
                'trailer'           => 'https://www.youtube.com/embed/EZjWp2wqWcg?si=MKfwqQ2HEYFa-zwy',
                'link_phim'         => 'https://www.youtube.com/embed/1c7U19UeZjw',
                'ngay_khoi_chieu'   => '2021-06-04',
                'ngay_ket_thuc'     => '2021-06-18',
                'trang_thai'        => 1,
                'created_at'        => '2021-06-04 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 1,
                'luot_xem'          => 200,
            ],
            [
                'ten_phim'          => 'Inception',
                'slug_phim'         => 'inception',
                'id_the_loai'       => 5,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://vov2.vov.vn/sites/default/files/styles/large/public/2021-09/1_-_inception.jpg',
                'dao_dien'          => 'Christopher Nolan',
                'dien_vien'         => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '148',
                'mo_ta'             => 'Inception là một bộ phim khoa học viễn tưởng kể về một nhóm người có khả năng xâm nhập vào giấc mơ của người khác để đánh cắp thông tin.',
                'trailer'           => 'https://www.youtube.com/embed/YoHD9XEInc0',
                'link_phim'         => 'https://www.youtube.com/embed/YoHD9XEInc0',
                'ngay_khoi_chieu'   => '2010-07-16',
                'ngay_ket_thuc'     => '2010-08-16',
                'trang_thai'        => 1,
                'created_at'        => '2010-07-16 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 1,
                'luot_xem'         => 20,
            ],
            [
                'ten_phim'          => 'Avatar',
                'slug_phim'         => 'avatar',
                'id_the_loai'       => 5,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://i1-vnexpress.vnecdn.net/2022/12/15/avatar-the-way-of-water-1671069183.jpg?w=330&h=495&q=100&dpr=1&fit=crop&s=YmqMRdbpi9-enYuczh3XiA',
                'dao_dien'          => 'James Cameron',
                'dien_vien'         => 'Sam Worthington, Zoe Saldana, Sigourney Weaver',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '162',
                'mo_ta'             => 'Avatar là một bộ phim khoa học viễn tưởng kể về cuộc phiêu lưu của một người lính bị liệt được gửi đến hành tinh Pandora.',
                'trailer'           => 'https://www.youtube.com/embed/5PSNL1qE6VY',
                'link_phim'         => 'https://www.youtube.com/embed/5PSNL1qE6VY',
                'ngay_khoi_chieu'   => '2009-12-18',
                'ngay_ket_thuc'     => '2010-01-18',
                'trang_thai'        => 1,
                'created_at'        => '2009-12-18 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 1,
                'luot_xem'         => 30,
            ],
            [
                'ten_phim'          => 'Titanic',
                'slug_phim'         => 'titanic',
                'id_the_loai'       => 2,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/vi/a/ab/Titanic_3D_poster_Vietnam.jpg',
                'dao_dien'          => 'James Cameron',
                'dien_vien'         => 'Leonardo DiCaprio, Kate Winslet, Billy Zane',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '195',
                'mo_ta'             => 'Titanic là một bộ phim lãng mạn kể về câu chuyện tình yêu giữa Jack và Rose trên con tàu Titanic định mệnh.',
                'trailer'           => 'https://www.youtube.com/embed/kVrqfYjkTdQ',
                'link_phim'         => 'https://www.youtube.com/embed/kVrqfYjkTdQ',
                'ngay_khoi_chieu'   => '1997-12-19',
                'ngay_ket_thuc'     => '1998-01-19',
                'trang_thai'        => 0,
                'created_at'        => '1997-12-19 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 40,
            ],
            [
                'ten_phim'          => 'The Dark Knight',
                'slug_phim'         => 'the-dark-knight',
                'id_the_loai'       => 9,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/vi/2/2d/Poster_phim_K%E1%BB%B5_s%C4%A9_b%C3%B3ng_%C4%91%C3%AAm_2008.jpg',
                'dao_dien'          => 'Christopher Nolan',
                'dien_vien'         => 'Christian Bale, Heath Ledger, Aaron Eckhart',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '152',
                'mo_ta'             => 'The Dark Knight là một bộ phim hành động kể về cuộc chiến giữa Batman và Joker để bảo vệ thành phố Gotham.',
                'trailer'           => 'https://www.youtube.com/embed/EXeTwQWrcwY',
                'link_phim'         => 'https://www.youtube.com/embed/EXeTwQWrcwY',
                'ngay_khoi_chieu'   => '2008-07-18',
                'ngay_ket_thuc'     => '2008-08-18',
                'trang_thai'        => 0,
                'created_at'        => '2008-07-18 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 50,
            ],
            [
                'ten_phim'          => 'Forrest Gump',
                'slug_phim'         => 'forrest-gump',
                'id_the_loai'       => 7,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/vi/1/1d/Forrest_gump.jpg',
                'dao_dien'          => 'Robert Zemeckis',
                'dien_vien'         => 'Tom Hanks, Robin Wright, Gary Sinise',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '142',
                'mo_ta'             => 'Forrest Gump là một bộ phim tâm lý kể về cuộc đời đầy biến động của Forrest Gump, một người đàn ông có trí tuệ thấp nhưng có trái tim nhân hậu.',
                'trailer'           => 'https://www.youtube.com/embed/bLvqoHBptjg',
                'link_phim'         => 'https://www.youtube.com/embed/bLvqoHBptjg',
                'ngay_khoi_chieu'   => '1994-07-06',
                'ngay_ket_thuc'     => '1994-08-06',
                'trang_thai'        => 0,
                'created_at'        => '1994-07-06 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 60,
            ],
            [
                'ten_phim'          => 'The Matrix',
                'slug_phim'         => 'the-matrix',
                'id_the_loai'       => 5,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/vi/c/c1/The_Matrix_Poster.jpg',
                'dao_dien'          => 'Lana Wachowski, Lilly Wachowski',
                'dien_vien'         => 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '136',
                'mo_ta'             => 'The Matrix là một bộ phim khoa học viễn tưởng kể về cuộc chiến giữa con người và máy móc trong một thế giới ảo.',
                'trailer'           => 'https://www.youtube.com/embed/vKQi3bBA1y8',
                'link_phim'         => 'https://www.youtube.com/embed/vKQi3bBA1y8',
                'ngay_khoi_chieu'   => '1999-03-31',
                'ngay_ket_thuc'     => '1999-04-30',
                'trang_thai'        => 0,
                'created_at'        => '1999-03-31 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 220,
            ],
            [
                'ten_phim'          => 'Gladiator',
                'slug_phim'         => 'gladiator',
                'id_the_loai'       => 6,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/vi/f/f8/GladiatorDVD.png',
                'dao_dien'          => 'Ridley Scott',
                'dien_vien'         => 'Russell Crowe, Joaquin Phoenix, Connie Nielsen',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '155',
                'mo_ta'             => 'Gladiator là một bộ phim lịch sử kể về cuộc đời của Maximus, một vị tướng La Mã bị phản bội và trở thành một đấu sĩ.',
                'trailer'           => 'https://www.youtube.com/embed/owK1qxDselE',
                'link_phim'         => 'https://www.youtube.com/embed/owK1qxDselE',
                'ngay_khoi_chieu'   => '2000-05-05',
                'ngay_ket_thuc'     => '2000-06-05',
                'trang_thai'        => 0,
                'created_at'        => '2000-05-05 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 20,
            ],
            [
                'ten_phim'          => 'The Shawshank Redemption',
                'slug_phim'         => 'the-shawshank-redemption',
                'id_the_loai'       => 7,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://vcdn1-giaitri.vnecdn.net/2022/03/31/shawshank-redemption-137394414-7901-5918-1648713782.jpg?w=680&h=0&q=100&dpr=1&fit=crop&s=NHDalOvuyN33Ug53_kOC2Q',
                'dao_dien'          => 'Frank Darabont',
                'dien_vien'         => 'Tim Robbins, Morgan Freeman, Bob Gunton',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '142',
                'mo_ta'             => 'The Shawshank Redemption là một bộ phim tâm lý kể về cuộc đời của Andy Dufresne, một người bị kết án oan và phải sống trong nhà tù Shawshank.',
                'trailer'           => 'https://www.youtube.com/embed/6hB3S9bIaco',
                'link_phim'         => 'https://www.youtube.com/embed/6hB3S9bIaco',
                'ngay_khoi_chieu'   => '1994-09-23',
                'ngay_ket_thuc'     => '1994-10-23',
                'trang_thai'        => 0,
                'created_at'        => '1994-09-23 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 10,
            ],
            [
                'ten_phim'          => 'The Lord of the Rings: The Return of the King',
                'slug_phim'         => 'the-lord-of-the-rings-the-return-of-the-king',
                'id_the_loai'       => 9,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/vi/0/07/CTNCN3.jpg',
                'dao_dien'          => 'Peter Jackson',
                'dien_vien'         => 'Elijah Wood, Viggo Mortensen, Ian McKellen',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '201',
                'mo_ta'             => 'The Lord of the Rings: The Return of the King là bộ phim cuối cùng trong series phim The Lord of the Rings kể về cuộc chiến giữa người và Orc để bảo vệ Middle Earth.',
                'trailer'           => 'https://www.youtube.com/embed/r5X-hFf6Bwo',
                'link_phim'         => 'https://www.youtube.com/embed/r5X-hFf6Bwo',
                'ngay_khoi_chieu'   => '2003-12-17',
                'ngay_ket_thuc'     => '2004-01-17',
                'trang_thai'        => 0,
                'created_at'        => '2003-12-17 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'The Godfather',
                'slug_phim'         => 'the-godfather',
                'id_the_loai'       => 7,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://kienviet.net/wp-content/uploads/2022/12/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
                'dao_dien'          => 'Francis Ford Coppola',
                'dien_vien'         => 'Marlon Brando, Al Pacino, James Caan',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '175',
                'mo_ta'             => 'The Godfather là một bộ phim tâm lý kể về cuộc đời của Don Vito Corleone, một ông trùm mafia nổi tiếng.',
                'trailer'           => 'https://www.youtube.com/embed/sY1S34973zA',
                'link_phim'         => 'https://www.youtube.com/embed/sY1S34973zA',
                'ngay_khoi_chieu'   => '1972-03-24',
                'ngay_ket_thuc'     => '1972-04-24',
                'trang_thai'        => 0,
                'created_at'        => '1972-03-24 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Cô Dâu Hào Môn',
                'slug_phim'         => 'co-dau-hao-mon',
                'id_the_loai'       => 3,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://style-republik.com/wp-content/uploads/2024/10/poster-phim-co-dau-hao-mon.jpg',
                'dao_dien'          => 'Vũ Ngọc Đãng',
                'dien_vien'         => 'Uyển Ân, Samuel An',
                'quoc_gia'          => 'Việt Nam',
                'thoi_luong'        => '120',
                'mo_ta'             => 'Cô Dâu Hào Môn là câu chuyện về một cô gái trẻ tên Tư Lạc giả làm quý tộc để kết hôn với một gia đình giàu có nhằm giúp gia đình thoát khỏi cảnh nghèo khó.',
                'trailer'           => 'https://www.youtube.com/embed/QJ8E9R70csY?si=Ukv8UloI2DwPHHT1',
                'link_phim'         => 'https://www.youtube.com/embed/example2',
                'ngay_khoi_chieu'   => '2025-01-15',
                'ngay_ket_thuc'     => '2025-02-15',
                'trang_thai'        => 0,
                'created_at'        => now(),
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Nụ Hôn Bạc Tỷ',
                'slug_phim'         => 'nu-hon-bac-ty',
                'id_the_loai'       => 2,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://bazaarvietnam.vn/wp-content/uploads/2024/11/BZ-phim-Tet-2025-Nu-hon-bac-ty-1.jpg',
                'dao_dien'          => 'Nguyễn Quang Dũng',
                'dien_vien'         => 'Ngô Thanh Vân, Johnny Trí Nguyễn, Kathy Uyên',
                'quoc_gia'          => 'Việt Nam',
                'thoi_luong'        => '115',
                'mo_ta'             => 'Nụ Hôn Bạc Tỷ là câu chuyện tình yêu đầy lãng mạn và thử thách giữa một cô gái nghèo và một chàng trai giàu có.',
                'trailer'           => 'https://www.youtube.com/embed/wr6MeifZCUs?si=QKyWdW_0gST3Tg7G',
                'link_phim'         => 'https://www.youtube.com/embed/example3',
                'ngay_khoi_chieu'   => '2025-02-14',
                'ngay_ket_thuc'     => '2025-03-14',
                'trang_thai'        => 0,
                'created_at'        => now(),
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Mai',
                'slug_phim'         => 'mai',
                'id_the_loai'       => 7,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://images2.thanhnien.vn/528068263637045248/2024/2/20/special-poster-2-mai-17084211313531000860296.jpg',
                'dao_dien'          => 'Trấn Thành',
                'dien_vien'         => 'Phương Anh Đào, Tuấn Trần, Trấn Thành, Ngọc Giàu',
                'quoc_gia'          => 'Việt Nam',
                'thoi_luong'        => '131',
                'mo_ta'             => 'Mai là một bộ phim tâm lý lãng mạn kể về cuộc đời của Mai, một người phụ nữ Việt Nam đã trải qua nhiều khó khăn trong cuộc sống.',
                'trailer'           => 'https://www.youtube.com/embed/HXWRTGbhb4U?si=y80rntVm9mW9DIRb',
                'link_phim'         => 'https://www.youtube.com/embed/example5',
                'ngay_khoi_chieu'   => '2024-02-10',
                'ngay_ket_thuc'     => '2024-03-10',
                'trang_thai'        => 0,
                'created_at'        => '2024-02-10 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Bố Già',
                'slug_phim'         => 'bo-gia',
                'id_the_loai'       => 7,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://media.vov.vn/sites/default/files/styles/large/public/2020-12/bo_gia_teaser_1_.jpg',
                'dao_dien'          => 'Trấn Thành, Vũ Ngọc Đãng',
                'dien_vien'         => 'Trấn Thành, Ngọc Giàu, Tuấn Trần, Ngân Chi, Lê Giang, Hoàng Mèo, Lan Phương, La Thành, Lê Trang, Quốc Khánh, A Quay, Bảo Phúc',
                'quoc_gia'          => 'Việt Nam',
                'thoi_luong'        => '128',
                'mo_ta'             => 'Bố Già là một bộ phim tâm lý hài hước kể về cuộc sống thường nhật của một xóm lao động nghèo và những hy sinh của Ba Sang để hỗ trợ gia đình mình.',
                'trailer'           => 'https://www.youtube.com/embed/jluSu8Rw6YE?si=360cYqGFmLxv2OX-',
                'link_phim'         => 'https://www.youtube.com/embed/oA-BhGNK7qw?si=fmg7sbonHXAkW2mc',
                'ngay_khoi_chieu'   => '2021-03-12',
                'ngay_ket_thuc'     => '2021-04-12',
                'trang_thai'        => 0,
                'created_at'        => '2021-03-12 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 3000,
            ],
            [
                'ten_phim'          => 'Quỷ Ăn Tạng 1',
                'slug_phim'         => 'quy-an-tang-1',
                'id_the_loai'       => 1,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://metiz.vn/media/poster_film/tee_yod_-_teaser_poster.jpg',
                'dao_dien'          => 'Taweewat Wantha',
                'dien_vien'         => 'Nadech Kugimiya, Jelilcha Kapaun, Rattawadee Wongthong',
                'quoc_gia'          => 'Thái Lan',
                'thoi_luong'        => '121',
                'mo_ta'             => 'Quỷ Ăn Tạng 1 kể về một linh hồn khát máu nhập vào một cô gái trẻ ở ngôi làng hẻo lánh, và anh trai cô phải tìm cách trục xuất linh hồn đó trước khi cô bị cái ác lấn át.',
                'trailer'           => 'https://www.youtube.com/embed/9jyPXIf4wVk?si=WDQyElvYPJzK2dm_',
                'link_phim'         => 'https://www.youtube.com/embed/example7',
                'ngay_khoi_chieu'   => '2023-10-26',
                'ngay_ket_thuc'     => '2023-11-26',
                'trang_thai'        => 0,
                'created_at'        => '2023-10-26 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 100,
            ],
            [
                'ten_phim'          => 'Quỷ Ăn Tạng 2',
                'slug_phim'         => 'quy-an-tang-2',
                'id_the_loai'       => 1,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://cinema.momocdn.net/img/50203322122973007-56744601924282197-Capture-2024-09-30-112200-compressed.jpg',
                'dao_dien'          => 'Taweewat Wantha',
                'dien_vien'         => 'Nadech Kugimiya, Denise Jelilcha Kappun, Kajbundit Jaidee, Peerakrit Phacharabunyakiat, Rattanawadee Wongthong',
                'quoc_gia'          => 'Thái Lan',
                'thoi_luong'        => '110',
                'mo_ta'             => 'Quỷ Ăn Tạng 2 tiếp tục câu chuyện về Yak, người vẫn kiên trì săn lùng linh hồn đen đã giết em gái mình. Yak phải đối mặt với những linh hồn ác độc và nguy hiểm để tiêu diệt linh hồn đen, đảm bảo nó không bao giờ quay lại hại gia đình anh.',
                'trailer'           => 'https://www.youtube.com/embed/xVVZvSybaEc?si=FNfyq6cn_FaWhQri',
                'link_phim'         => 'https://www.youtube.com/embed/example8',
                'ngay_khoi_chieu'   => '2024-10-10',
                'ngay_ket_thuc'     => '2024-11-10',
                'trang_thai'        => 0,
                'created_at'        => '2024-10-10 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 200,
            ],
            [
                'ten_phim'          => 'Bộ Tứ Báo Thù',
                'slug_phim'         => 'bo-tu-bao-thu',
                'id_the_loai'       => 3,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://images2.thanhnien.vn/528068263637045248/2024/10/24/edit-btbtposter1stlook-1729746482882705245885.jpeg',
                'dao_dien'          => 'Trấn Thành',
                'dien_vien'         => 'Trấn Thành, Lê Giang, Lê Dương Bảo Lâm, Uyển Ân',
                'quoc_gia'          => 'Việt Nam',
                'thoi_luong'        => '132',
                'mo_ta'             => 'Bộ Tứ Báo Thù là câu chuyện về bốn người bạn thân cùng nhau thực hiện những phi vụ hài hước và lãng mạn trong dịp Tết.',
                'trailer'           => 'https://www.youtube.com/embed/zKMOgOWn8lQ?si=OcWpAo8V3rTZPcnb',
                'link_phim'         => 'https://www.youtube.com/embed/example8',
                'ngay_khoi_chieu'   => '2025-01-29',
                'ngay_ket_thuc'     => '2025-02-28',
                'trang_thai'        => 0,
                'created_at'        => now(),
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 2500,
            ],
            [
                'ten_phim'          => 'Yêu Nhầm Bạn Thân',
                'slug_phim'         => 'yeu-nham-ban-than',
                'id_the_loai'       => 2,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/3/image/1800x/71252117777b696995f01934522c402d/t/e/teaser_cinema_1_.jpg',
                'dao_dien'          => 'Nguyễn Quang Dũng, Diệp Thế Vinh',
                'dien_vien'         => 'Kaity Nguyễn, Trần Ngọc Vàng, Thanh Sơn, Quốc Khánh, Phương Nam, Stephen Turban',
                'quoc_gia'          => 'Việt Nam',
                'thoi_luong'        => '110',
                'mo_ta'             => 'Yêu Nhầm Bạn Thân kể câu chuyện tình yêu lãng mạn giữa khung cảnh tuyệt đẹp của Việt Nam, từ bờ cát trắng miền Trung đến núi rừng Tây Bắc. Bình An, một cô gái sống hết mình vì tình yêu, đang hạnh phúc bên bạn trai Vũ Trần, một đạo diễn tài năng nhưng đào hoa. Bên cạnh cô là Bảo Toàn, người bạn thân lặng thầm yêu cô từ lâu.',
                'trailer'           => 'https://www.youtube.com/embed/Z7AbUpnfcW8?si=JT7OMxOEfVuwsi_b',
                'link_phim'         => 'https://www.youtube.com/embed/example2',
                'ngay_khoi_chieu'   => '2025-01-29',
                'ngay_ket_thuc'     => '2025-02-28',
                'trang_thai'        => 0,
                'created_at'        => now(),
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 1342,
            ],
            [
                'ten_phim'          => 'Nhà Gia Tiên',
                'slug_phim'         => 'nha-gia-tien',
                'id_the_loai'       => 7,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://cinestar.com.vn/_next/image/?url=https%3A%2F%2Fapi-website.cinestar.com.vn%2Fmedia%2Fwysiwyg%2FPosters%2F02_2025%2Fnha-gia-tien-sneak.jpg&w=3840&q=75',
                'dao_dien'          => 'Huỳnh Lập',
                'dien_vien'         => 'Phương Mỹ Chi, Huỳnh Lập, NSƯT Hạnh Thúy, NSƯT Huỳnh Đông, Puka',
                'quoc_gia'          => 'Việt Nam',
                'thoi_luong'        => '120',
                'mo_ta'             => 'Nhà Gia Tiên là một bộ phim tâm lý hài hước kể về hành trình khám phá tình cảm gia đình giữa các thế hệ, với sự góp mặt của hai nhân vật chính, Gia Minh và Mỹ Tiên.',
                'trailer'           => 'https://www.youtube.com/embed/hXGozmNBwt4?si=C5HHPh6IGinfi9XF',
                'link_phim'         => 'https://www.youtube.com/embed/example9',
                'ngay_khoi_chieu'   => '2025-02-21',
                'ngay_ket_thuc'     => '2025-03-21',
                'trang_thai'        => 0,
                'created_at'        => now(),
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 2332,
            ],
            [
                'ten_phim'          => 'Nhà Bà Nữ',
                'slug_phim'         => 'nha-ba-nu',
                'id_the_loai'       => 7,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/vi/6/6f/%C3%81p_ph%C3%ADch_phim_Nh%C3%A0_b%C3%A0_N%E1%BB%AF.jpg',
                'dao_dien'          => 'Trấn Thành',
                'dien_vien'         => 'Lê Giang, Uyển Ân, Song Luân, Trấn Thành, Khả Như, Quỳnh Lý, Phương Lan, Dương Lâm, Ngọc Giàu, Việt Anh',
                'quoc_gia'          => 'Việt Nam',
                'thoi_luong'        => '103',
                'mo_ta'             => 'Nhà Bà Nữ là một bộ phim hài chính kịch kể về những xung đột trong gia đình bà Ngọc Nữ, người điều hành một quán bún riêu cua trong một khu chung cư cũ.',
                'trailer'           => 'https://www.youtube.com/embed/IkaP0KJWTsQ?si=t7b7HC41LW8K1n_v',
                'link_phim'         => 'https://www.youtube.com/embed/example9',
                'ngay_khoi_chieu'   => '2023-01-22',
                'ngay_ket_thuc'     => '2023-02-22',
                'trang_thai'        => 0,
                'created_at'        => '2023-01-22 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 2341,
            ],


            [
                'ten_phim'          => 'Mad Max: Fury Road',
                'slug_phim'         => 'mad-max-fury-road',
                'id_the_loai'       => 9,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/vi/2/23/Max_Mad_Fury_Road_Newest_Poster.jpg',
                'dao_dien'          => 'George Miller',
                'dien_vien'         => 'Tom Hardy, Charlize Theron, Nicholas Hoult',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '120',
                'mo_ta'             => 'Mad Max: Fury Road là một bộ phim hành động hậu tận thế về cuộc chiến sinh tồn trong một thế giới hoang tàn.',
                'trailer'           => 'https://www.youtube.com/embed/j3xFZkRr4Fg?si=tujGH6mFWhTB61e7',
                'link_phim'         => 'https://www.youtube.com/embed/hEJnMQG9ev8',
                'ngay_khoi_chieu'   => '2015-05-15',
                'ngay_ket_thuc'     => '2015-06-15',
                'trang_thai'        => 0,
                'created_at'        => '2015-05-15 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'John Wick',
                'slug_phim'         => 'john-wick',
                'id_the_loai'       => 9,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://taynguyenfilm.com/wp-content/uploads/2023/03/review-phim-john-wick-4-cuoc-chien-song-con-1.jpg',
                'dao_dien'          => 'Chad Stahelski',
                'dien_vien'         => 'Keanu Reeves, Michael Nyqvist, Alfie Allen',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '101',
                'mo_ta'             => 'John Wick là một bộ phim hành động về một sát thủ huyền thoại trở lại để trả thù cho cái chết của chú chó yêu quý của mình.',
                'trailer'           => 'https://www.youtube.com/embed/HEMAtgEojgk?si=KJycKeGLgv7-C0jK',
                'link_phim'         => 'https://www.youtube.com/embed/2AUmvWm5ZDQ',
                'ngay_khoi_chieu'   => '2014-10-24',
                'ngay_ket_thuc'     => '2014-11-24',
                'trang_thai'        => 0,
                'created_at'        => '2014-10-24 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'The Raid: Redemption',
                'slug_phim'         => 'the-raid-redemption',
                'id_the_loai'       => 9,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://play-lh.googleusercontent.com/yaKmVrl_7fZhLqY0YuNUjl-oMuKR737um4kBfNkZTs5JjXymK3CMxlL-HG2jnPH1jxK3=w240-h480-rw',
                'dao_dien'          => 'Gareth Evans',
                'dien_vien'         => 'Iko Uwais, Joe Taslim, Donny Alamsyah',
                'quoc_gia'          => 'Indonesia',
                'thoi_luong'        => '101',
                'mo_ta'             => 'The Raid: Redemption là một bộ phim hành động về một đội cảnh sát đặc nhiệm phải chiến đấu để sống sót trong một tòa nhà đầy tội phạm.',
                'trailer'           => 'https://www.youtube.com/embed/MaYsGJbP7Tg?si=IgT82LtX5Z7KCb35',
                'link_phim'         => 'https://www.youtube.com/embed/6f6f_kfp1Z8',
                'ngay_khoi_chieu'   => '2011-09-08',
                'ngay_ket_thuc'     => '2011-10-08',
                'trang_thai'        => 0,
                'created_at'        => '2011-09-08 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],


            [
                'ten_phim'          => 'Late Night with the Devil',
                'slug_phim'         => 'late-night-with-the-devil',
                'id_the_loai'       => 1,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cb/Late_Night_with_the_Devil_poster.jpg/220px-Late_Night_with_the_Devil_poster.jpg',
                'dao_dien'          => 'Colin Cairnes, Cameron Cairnes',
                'dien_vien'         => 'David Dastmalchian, Laura Gordon, Fayssal Bazzi',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '97',
                'mo_ta'             => 'Late Night with the Devil là một bộ phim kinh dị về một chương trình talk show bị ám bởi quỷ dữ.',
                'trailer'           => 'https://www.youtube.com/embed/cvt-mauboTc?si=MDU48kSgsb9cy0dG',
                'link_phim'         => 'https://www.youtube.com/embed/cvt-mauboTc?si=MDU48kSgsb9cy0dG',
                'ngay_khoi_chieu'   => '2024-01-15',
                'ngay_ket_thuc'     => '2024-02-15',
                'trang_thai'        => 0,
                'created_at'        => '2024-01-15 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Oddity',
                'slug_phim'         => 'oddity',
                'id_the_loai'       => 1,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://khenphim.com/wp-content/uploads/2024/09/Oddity-pic1-poster_KP-scaled.webp',
                'dao_dien'          => 'Damian McCarthy',
                'dien_vien'         => 'Gwilym Lee, Carolyn Bracken, Tadhg Murphy',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '96',
                'mo_ta'             => 'Oddity là một bộ phim kinh dị về một ngôi nhà bị ám và những bí ẩn xung quanh cái chết của một người phụ nữ.',
                'trailer'           => 'https://www.youtube.com/embed/tLNDvnv8B3A?si=YMh0MYo2EjYir2Jv',
                'link_phim'         => 'https://www.youtube.com/embed/tLNDvnv8B3A?si=YMh0MYo2EjYir2Jv',
                'ngay_khoi_chieu'   => '2024-02-10',
                'ngay_ket_thuc'     => '2024-03-10',
                'trang_thai'        => 0,
                'created_at'        => '2024-02-10 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Infested',
                'slug_phim'         => 'infested',
                'id_the_loai'       => 1,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR5Yxc9LEs8TkW8I9HUOpXC0_QJRtvNBXE-SQ0LG90i70nXyrSudHVn_SMMZEQqurxv84&usqp=CAU',
                'dao_dien'          => 'Sébastien Vaniček',
                'dien_vien'         => 'Théo Christine, Sofia Lesaffre, Jérôme Niel',
                'quoc_gia'          => 'Pháp',
                'thoi_luong'        => '95',
                'mo_ta'             => 'Infested là một bộ phim kinh dị về một người đàn ông bị mắc kẹt trong một ngôi nhà đầy côn trùng nguy hiểm.',
                'trailer'           => 'https://www.youtube.com/embed/8URLr27sbE0?si=otulKoWVy8S8-MTt',
                'link_phim'         => 'https://www.youtube.com/embed/8URLr27sbE0?si=otulKoWVy8S8-MTt',
                'ngay_khoi_chieu'   => '2024-03-05',
                'ngay_ket_thuc'     => '2024-04-05',
                'trang_thai'        => 0,
                'created_at'        => '2024-03-05 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],

            [
                'ten_phim'          => 'Furiosa: A Mad Max Saga',
                'slug_phim'         => 'furiosa-a-mad-max-saga',
                'id_the_loai'       => 4,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://cinema.momocdn.net/img/28296105861591899-ol7Xf7dWVzhJ20b7bJi451TvPt.jpg',
                'dao_dien'          => 'George Miller',
                'dien_vien'         => 'Anya Taylor-Joy, Chris Hemsworth, Tom Burke',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '148',
                'mo_ta'             => 'Furiosa: A Mad Max Saga là câu chuyện về nguồn gốc của chiến binh Furiosa trước khi cô gặp và hợp tác với Mad Max.',
                'trailer'           => 'https://www.youtube.com/embed/FVswuip0-co?si=bcRm1T6egEKpj_p2',
                'link_phim'         => 'https://www.youtube.com/embed/FVswuip0-co?si=bcRm1T6egEKpj_p2',
                'ngay_khoi_chieu'   => '2024-05-15',
                'ngay_ket_thuc'     => '2024-06-15',
                'trang_thai'        => 0,
                'created_at'        => '2024-05-15 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Arthur the King',
                'slug_phim'         => 'arthur-the-king',
                'id_the_loai'       => 4,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://i1-vnexpress.vnecdn.net/2024/05/08/arthur-the-king-1715162029.jpg?w=330&h=495&q=100&dpr=1&fit=crop&s=sCPHt_F-BHpYb9v_KMgLcg',
                'dao_dien'          => 'Simon Cellan Jones',
                'dien_vien'         => 'Mark Wahlberg, Simu Liu, Juliet Rylance',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '107',
                'mo_ta'             => 'Arthur the King là một bộ phim phiêu lưu về một tay đua mạo hiểm nhận nuôi một chú chó hoang tên Arthur để cùng tham gia vào một cuộc đua sức bền.',
                'trailer'           => 'https://www.youtube.com/embed/wjDJNEPghNY?si=JSr0ZzTwqnGKCzSI',
                'link_phim'         => 'https://www.youtube.com/embed/wjDJNEPghNY?si=JSr0ZzTwqnGKCzSI',
                'ngay_khoi_chieu'   => '2024-06-10',
                'ngay_ket_thuc'     => '2024-07-10',
                'trang_thai'        => 0,
                'created_at'        => '2024-06-10 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Deadpool & Wolverine',
                'slug_phim'         => 'deadpool-wolverine',
                'id_the_loai'       => 4,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://i1-vnexpress.vnecdn.net/2024/07/30/deadpool--wolverine-1722323470.jpg?w=330&h=495&q=100&dpr=1&fit=crop&s=alPLRnlhuPa81IRQZ4Um7A',
                'dao_dien'          => 'Shawn Levy',
                'dien_vien'         => 'Ryan Reynolds, Hugh Jackman, Emma Corrin',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '128',
                'mo_ta'             => 'Deadpool & Wolverine là một bộ phim phiêu lưu về Deadpool được mời vào Vũ trụ Điện ảnh Marvel bởi Cơ quan Thời gian, nhưng thay vào đó anh ta tuyển dụng một biến thể của Wolverine để cứu vũ trụ của mình khỏi sự diệt vong.',
                'trailer'           => 'https://www.youtube.com/embed/73_1biulkYk?si=3ldoUdGUQDtDfNCe',
                'link_phim'         => 'https://www.youtube.com/embed/73_1biulkYk?si=3ldoUdGUQDtDfNCe',
                'ngay_khoi_chieu'   => '2024-07-20',
                'ngay_ket_thuc'     => '2024-08-20',
                'trang_thai'        => 0,
                'created_at'        => '2024-07-20 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Dune: Part Two',
                'slug_phim'         => 'dune-part-two',
                'id_the_loai'       => 4,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/vi/9/94/Dune_2_VN_poster.jpg',
                'dao_dien'          => 'Denis Villeneuve',
                'dien_vien'         => 'Timothée Chalamet, Zendaya, Rebecca Ferguson',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '166',
                'mo_ta'             => 'Dune: Part Two là phần tiếp theo của bộ phim Dune, kể về Paul Atreides hợp nhất với người Fremen trong cuộc hành trình báo thù chống lại những kẻ âm mưu đã hủy diệt gia đình anh.',
                'trailer'           => 'https://www.youtube.com/embed/Way9Dexny3w?si=SW-ExfpUf5sWeF1u',
                'link_phim'         => 'https://www.youtube.com/embed/Way9Dexny3w?si=SW-ExfpUf5sWeF1u',
                'ngay_khoi_chieu'   => '2024-11-15',
                'ngay_ket_thuc'     => '2024-12-15',
                'trang_thai'        => 0,
                'created_at'        => '2024-11-15 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],

            [
                'ten_phim'          => 'Transformers One',
                'slug_phim'         => 'transformers-one',
                'id_the_loai'       => 8,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://bhdstar.vn/wp-content/uploads/2024/09/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-13.jpg',
                'dao_dien'          => 'Josh Cooley',
                'dien_vien'         => 'Chris Hemsworth, Brian Tyree Henry, Scarlett Johansson',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '120',
                'mo_ta'             => 'Transformers One là một bộ phim giả tưởng về cuộc chiến giữa các robot biến hình Optimus Prime và Megatron.',
                'trailer'           => 'https://www.youtube.com/embed/0I2_qPsthDA?si=qii4e3rVJPJhrVfW',
                'link_phim'         => 'https://www.youtube.com/embed/0I2_qPsthDA?si=qii4e3rVJPJhrVfW',
                'ngay_khoi_chieu'   => '2024-05-15',
                'ngay_ket_thuc'     => '2024-06-15',
                'trang_thai'        => 0,
                'created_at'        => '2024-05-15 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Wicked',
                'slug_phim'         => 'wicked',
                'id_the_loai'       => 8,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/w/k/wkd_forestduo_470x700.jpg',
                'dao_dien'          => 'Jon M. Chu',
                'dien_vien'         => 'Cynthia Erivo, Ariana Grande, Jonathan Bailey',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '140',
                'mo_ta'             => 'Wicked là một bộ phim giả tưởng về mối quan hệ phức tạp giữa hai phù thủy Elphaba và Glinda trước khi trở thành kẻ thù.',
                'trailer'           => 'https://www.youtube.com/embed/IILf3ZEBnmM?si=0BR7e-3oSvAoKA_J',
                'link_phim'         => 'https://www.youtube.com/embed/IILf3ZEBnmM?si=0BR7e-3oSvAoKA_J',
                'ngay_khoi_chieu'   => '2024-11-22',
                'ngay_ket_thuc'     => '2024-12-22',
                'trang_thai'        => 0,
                'created_at'        => '2024-11-22 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Ghostbusters: Frozen Empire',
                'slug_phim'         => 'ghostbusters-frozen-empire',
                'id_the_loai'       => 8,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://www.bhdstar.vn/wp-content/uploads/2024/04/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-30.jpg',
                'dao_dien'          => 'Gil Kenan',
                'dien_vien'         => 'Paul Rudd, Carrie Coon, Finn Wolfhard',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '124',
                'mo_ta'             => 'Ghostbusters: Frozen Empire là một bộ phim giả tưởng về nhóm Ghostbusters phải đối mặt với một mối đe dọa siêu nhiên mới từ một đế chế băng giá.',
                'trailer'           => 'https://www.youtube.com/embed/HpOBXh02rVc?si=rxmePWFwWKzLpeAI',
                'link_phim'         => 'https://www.youtube.com/embed/HpOBXh02rVc?si=rxmePWFwWKzLpeAI',
                'ngay_khoi_chieu'   => '2024-07-10',
                'ngay_ket_thuc'     => '2024-08-10',
                'trang_thai'        => 0,
                'created_at'        => '2024-07-10 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,

            ],
            [
                'ten_phim'          => 'The Little Mermaid',
                'slug_phim'         => 'the-little-mermaid',
                'id_the_loai'       => 8,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://i1-vnexpress.vnecdn.net/2023/05/28/nang-tien-ca-1685269000.jpg?w=330&h=495&q=100&dpr=1&fit=crop&s=lGOWIGDqy677jbUAme6hyA',
                'dao_dien'          => 'Rob Marshall',
                'dien_vien'         => 'Halle Bailey, Jonah Hauer-King, Melissa McCarthy',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '135',
                'mo_ta'             => 'The Little Mermaid là một bộ phim giả tưởng về nàng tiên cá Ariel và cuộc hành trình của cô để trở thành con người và tìm kiếm tình yêu.',
                'trailer'           => 'https://www.youtube.com/embed/kpGo2_d3oYE?si=sOaj--wJ7SQx9Z66',
                'link_phim'         => 'https://www.youtube.com/embed/kpGo2_d3oYE?si=sOaj--wJ7SQx9Z66',
                'ngay_khoi_chieu'   => '2024-05-26',
                'ngay_ket_thuc'     => '2024-06-26',
                'trang_thai'        => 0,
                'created_at'        => '2024-05-26 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],

            [
                'ten_phim'          => 'The Lord of the Rings: The War of the Rohirrim',
                'slug_phim'         => 'the-lord-of-the-rings-the-war-of-the-rohirrim',
                'id_the_loai'       => 10,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/vi/8/8b/THE_LORD_OF_THE_RINGS_in_THE_WAR_OF_THE_ROHIRRIM_%E2%80%93_Vietnam_poster.jpg',
                'dao_dien'          => 'Kenji Kamiyama',
                'dien_vien'         => 'Brian Cox, Miranda Otto, Gaia Wise',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '120',
                'mo_ta'             => 'The Lord of the Rings: The War of the Rohirrim là một bộ phim thần thoại kể về cuộc chiến của người Rohirrim chống lại kẻ thù để bảo vệ vương quốc của họ.',
                'trailer'           => 'https://www.youtube.com/embed/ST08liEjNsw?si=rEIKZmn6R_bCRF5f',
                'link_phim'         => 'https://www.youtube.com/embed/ST08liEjNsw?si=rEIKZmn6R_bCRF5f',
                'ngay_khoi_chieu'   => '2024-04-12',
                'ngay_ket_thuc'     => '2024-05-12',
                'trang_thai'        => 0,
                'created_at'        => '2024-04-12 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Percy Jackson and the Olympians: The Lightning Thief',
                'slug_phim'         => 'percy-jackson-the-lightning-thief',
                'id_the_loai'       => 10,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/vi/e/eb/Percy_Jackson_%26_the_Olympians_The_Lightning_Thief_poster.jpg',
                'dao_dien'          => 'James Bobin',
                'dien_vien'         => 'Walker Scobell, Leah Sava Jeffries, Aryan Simhadri',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '118',
                'mo_ta'             => 'Percy Jackson and the Olympians: The Lightning Thief là một bộ phim thần thoại về một cậu bé phát hiện ra mình là con trai của thần Poseidon và phải ngăn chặn một cuộc chiến giữa các vị thần.',
                'trailer'           => 'https://www.youtube.com/embed/R86InkfdboA?si=Ctxd0OZPjmH45ycc',
                'link_phim'         => 'https://www.youtube.com/embed/R86InkfdboA?si=Ctxd0OZPjmH45ycc',
                'ngay_khoi_chieu'   => '2024-06-15',
                'ngay_ket_thuc'     => '2024-07-15',
                'trang_thai'        => 0,
                'created_at'        => '2024-06-15 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'The Tigers Apprentice',
                'slug_phim'         => 'the-tigers-apprentice',
                'id_the_loai'       => 10,
                'loai_phim'         => 1,
                'hinh_anh'          => 'https://play-lh.googleusercontent.com/D2dWh3PiUFufa03BWDgvbD9iZhR1GXxwk2kIHTJNqgkCHsK5kV5GLyz9fgq1RPahLBmDSVNY-jS6at9LFg',
                'dao_dien'          => 'Carlos Baena',
                'dien_vien'         => 'Henry Golding, Sandra Oh, Michelle Yeoh',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '110',
                'mo_ta'             => 'The Tigers Apprentice là một bộ phim thần thoại về một cậu bé được một con hổ thần bí huấn luyện để bảo vệ một viên ngọc quý khỏi những thế lực đen tối.',
                'trailer'           => 'https://www.youtube.com/embed/GGJnmXpT3Og?si=UCegQAPA-luQwK1B',
                'link_phim'         => 'https://www.youtube.com/embed/GGJnmXpT3Og?si=UCegQAPA-luQwK1B',
                'ngay_khoi_chieu'   => '2024-08-10',
                'ngay_ket_thuc'     => '2024-09-10',
                'trang_thai'        => 0,
                'created_at'        => '2024-08-10 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            // Phim Bộ
            [
                'ten_phim'          => 'Grotesquerie',
                'slug_phim'         => 'grotesquerie',
                'id_the_loai'       => 1,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWSqKWiIW76qLWUlRDPYupdvglL4lyYZ64Sw&s',
                'dao_dien'          => 'Ryan Murphy',
                'dien_vien'         => 'Niecy Nash, Micaela Diamond, Nicholas Alexander Chavez',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '45',
                'mo_ta'             => 'Grotesquerie là một bộ phim kinh dị về một thị trấn nhỏ nơi một kẻ giết người hàng loạt đang săn lùng mọi người. Thám tử Lois Tryon, cùng với một nữ tu và một linh mục, phải đối mặt với những bí ẩn đen tối của thị trấn.',
                'trailer'           => 'https://www.youtube.com/embed/daV1NI7hxY0?si=NaD37C0T0zybjlqd',
                'link_phim'         => 'https://www.youtube.com/embed/daV1NI7hxY0?si=NaD37C0T0zybjlqd',
                'ngay_khoi_chieu'   => '2024-10-01',
                'ngay_ket_thuc'     => '2024-12-01',
                'trang_thai'        => 0,
                'created_at'        => '2024-10-01 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 321,
            ],
            [
                'ten_phim'          => 'Uzumaki',
                'slug_phim'         => 'uzumaki',
                'id_the_loai'       => 1,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2NhEWejo1hL5W8XmcKHvLYHypfP_zkmuEQA&s',
                'dao_dien'          => 'Hiroshi Nagahama',
                'dien_vien'         => 'Kirie Goshima, Shuichi Saito',
                'quoc_gia'          => 'Nhật Bản',
                'thoi_luong'        => '30',
                'mo_ta'             => 'Uzumaki là một bộ phim kinh dị dựa trên manga nổi tiếng của Junji Ito, kể về hai học sinh trung học chứng kiến thị trấn của họ bắt đầu tự hủy diệt bởi những hiện tượng kỳ lạ và đáng sợ.',
                'trailer'           => 'https://www.youtube.com/embed/2ivmweJQaco?si=FB8sBPjRzxOy8kg-',
                'link_phim'         => 'https://www.youtube.com/embed/2ivmweJQaco?si=FB8sBPjRzxOy8kg-',
                'ngay_khoi_chieu'   => '2024-11-15',
                'ngay_ket_thuc'     => '2025-01-15',
                'trang_thai'        => 0,
                'created_at'        => now(),
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 4323,
            ],
            [
                'ten_phim'          => 'Like Water for Chocolate',
                'slug_phim'         => 'like-water-for-chocolate',
                'id_the_loai'       => 2,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://image.tmdb.org/t/p/w500/18WIVssvDsnlXRpLSx0oY9Ga5Xi.jpg',
                'dao_dien'          => 'Jerry Rodriguez Burckle',
                'dien_vien'         => 'Azul Guaita, Andres Baida, Irene Azuela',
                'quoc_gia'          => 'Mexico',
                'thoi_luong'        => '50',
                'mo_ta'             => 'Like Water for Chocolate là một bộ phim lãng mạn về tình yêu bị ngăn cấm giữa Tita và Pedro, được thể hiện qua những món ăn kỳ diệu của Tita.',
                'trailer'           => 'https://www.youtube.com/embed/NeVLROw2SEo?si=oTiwsQbAlfrhBIse',
                'link_phim'         => 'https://www.youtube.com/embed/NeVLROw2SEo?si=oTiwsQbAlfrhBIse',
                'ngay_khoi_chieu'   => '2024-01-10',
                'ngay_ket_thuc'     => '2024-03-10',
                'trang_thai'        => 0,
                'created_at'        => '2024-01-10 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 634,
            ],
            [
                'ten_phim'          => 'Alice & Jack',
                'slug_phim'         => 'alice-and-jack',
                'id_the_loai'       => 2,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://m.media-amazon.com/images/M/MV5BMjAwZDczNGUtYjUwMC00NGNhLTlkYWYtYzY4OGNkZmQwYjk2XkEyXkFqcGc@._V1_.jpg',
                'dao_dien'          => 'Victor Levin',
                'dien_vien'         => 'Andrea Riseborough, Domhnall Gleeson, Aisling Bea',
                'quoc_gia'          => 'Anh',
                'thoi_luong'        => '45',
                'mo_ta'             => 'Alice & Jack là một bộ phim lãng mạn về mối quan hệ kéo dài 16 năm của Alice và Jack, với những thăng trầm của cuộc sống.',
                'trailer'           => 'https://www.youtube.com/embed/nWygMDGlxDI?si=uI2xlWeeX2e55aMm',
                'link_phim'         => 'https://www.youtube.com/embed/nWygMDGlxDI?si=uI2xlWeeX2e55aMm',
                'ngay_khoi_chieu'   => '2024-04-15',
                'ngay_ket_thuc'     => '2024-06-15',
                'trang_thai'        => 0,
                'created_at'        => '2024-04-15 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 556,
            ],
            [
                'ten_phim'          => 'High Potential',
                'slug_phim'         => 'high-potential',
                'id_the_loai'       => 3,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://i.pinimg.com/474x/7f/71/ce/7f71ceee7d71bb398f9ac45bf63eb94b.jpg',
                'dao_dien'          => 'Michael Spiller',
                'dien_vien'         => 'Kaitlin Olson, Daniel Sunjata, Javicia Leslie',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '45',
                'mo_ta'             => 'High Potential là một bộ phim hài về một bà mẹ đơn thân với khả năng giải quyết tội phạm độc đáo, dẫn đến một mối quan hệ đối tác bất ngờ với một thám tử.',
                'trailer'           => 'https://www.youtube.com/embed/W6zbdYNg9Rs?si=X1in2GBr-IyytFGs',
                'link_phim'         => 'https://www.youtube.com/embed/W6zbdYNg9Rs?si=X1in2GBr-IyytFGs',
                'ngay_khoi_chieu'   => '2024-09-17',
                'ngay_ket_thuc'     => '2024-12-17',
                'trang_thai'        => 0,
                'created_at'        => '2024-09-17 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 746,
            ],
            [
                'ten_phim'          => 'A Man on the Inside',
                'slug_phim'         => 'a-man-on-the-inside',
                'id_the_loai'       => 3,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://m.media-amazon.com/images/M/MV5BYzgwOGIwZjAtZTg0OS00ZGRkLTgxMjUtMjU2NDA2Yjc4NTc1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
                'dao_dien'          => 'Dean Holland',
                'dien_vien'         => 'Ted Danson, Mary Elizabeth Ellis, Stephanie Beatriz',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '50',
                'mo_ta'             => 'A Man on the Inside là một bộ phim hài về một thám tử tư thuê một giáo sư đã nghỉ hưu để làm gián điệp trong một nhà dưỡng lão.',
                'trailer'           => 'https://www.youtube.com/embed/xhsVj_4ONoA?si=mJtjPBTNx2jZyjDA',
                'link_phim'         => 'https://www.youtube.com/embed/xhsVj_4ONoA?si=mJtjPBTNx2jZyjDA',
                'ngay_khoi_chieu'   => '2024-11-21',
                'ngay_ket_thuc'     => '2025-02-21',
                'trang_thai'        => 0,
                'created_at'        => now(),
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 1456,
            ],
            [
                'ten_phim'          => 'Shogun',
                'slug_phim'         => 'shogun',
                'id_the_loai'       => 4,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://cdn0-production-images-kly.akamaized.net/WrQ5TZ9Z8P96u9cSGzF2qqcyQ5c=/800x1066/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/4835838/original/090795500_1716026830-MV5BMTdiOTdhNDQtNTJmMi00YTdkLThkYTAtODg0YTUxYjcxMjc3XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg',
                'dao_dien'          => 'Justin Marks',
                'dien_vien'         => 'Cosmo Jarvis, Hiroyuki Sanada, Anna Sawai',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '60',
                'mo_ta'             => 'Shogun là một bộ phim phiêu lưu lịch sử dựa trên tiểu thuyết nổi tiếng của James Clavell, kể về cuộc xung đột văn hóa giữa châu Âu và Nhật Bản trong thời kỳ chiến tranh.',
                'trailer'           => 'https://www.youtube.com/embed/yAN5uspO_hk?si=hAixQElpFdQV2Zyw',
                'link_phim'         => 'https://www.youtube.com/embed/yAN5uspO_hk?si=hAixQElpFdQV2Zyw',
                'ngay_khoi_chieu'   => '2024-01-15',
                'ngay_ket_thuc'     => '2024-04-15',
                'trang_thai'        => 0,
                'created_at'        => '2024-01-15 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 2654,
            ],
            [
                'ten_phim'          => 'Skeleton Crew',
                'slug_phim'         => 'skeleton-crew',
                'id_the_loai'       => 4,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://subnhanh.moi/wp-content/uploads/2025/02/star-wars-skeleton-crew-13341-thumb.webp',
                'dao_dien'          => 'Jon Watts',
                'dien_vien'         => 'Jude Law, Ravi Cabot-Conyers, Kyriana Kratter',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '50',
                'mo_ta'             => 'Skeleton Crew là một bộ phim phiêu lưu trong vũ trụ Star Wars, kể về bốn đứa trẻ bị lạc trong thiên hà sau sự kiện Return of the Jedi và phải tìm cách trở về nhà.',
                'trailer'           => 'https://www.youtube.com/embed/f19gfOMZTtg?si=UCGJFN-RM-yO1TA8',
                'link_phim'         => 'https://www.youtube.com/embed/f19gfOMZTtg?si=UCGJFN-RM-yO1TA8',
                'ngay_khoi_chieu'   => '2024-05-20',
                'ngay_ket_thuc'     => '2024-08-20',
                'trang_thai'        => 0,
                'created_at'        => '2024-05-20 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Nautilus',
                'slug_phim'         => 'nautilus',
                'id_the_loai'       => 5,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://s9.opensubtitles.com/features/2/3/0/2151032.jpg',
                'dao_dien'          => 'Michael Matthews',
                'dien_vien'         => 'Shazad Latif, Georgia Flood, Thierry Frémont',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '50',
                'mo_ta'             => 'Nautilus là một bộ phim viễn tưởng kể về cuộc phiêu lưu của thuyền trưởng Nemo và thủy thủ đoàn của tàu ngầm Nautilus khi họ khám phá những bí ẩn dưới lòng đại dương.',
                'trailer'           => 'https://www.youtube.com/embed/tK7bWr3YwNU?si=mOa5nurgRIp_5A-I',
                'link_phim'         => 'https://www.youtube.com/embed/tK7bWr3YwNU?si=mOa5nurgRIp_5A-I',
                'ngay_khoi_chieu'   => '2024-02-10',
                'ngay_ket_thuc'     => '2024-05-10',
                'trang_thai'        => 0,
                'created_at'        => '2024-02-10 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'The Peripheral',
                'slug_phim'         => 'the-peripheral',
                'id_the_loai'       => 5,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://image.tmdb.org/t/p/w342/2e5NNQu9B1fXBNllRj8fzysCguP.jpg',
                'dao_dien'          => 'Vincenzo Natali',
                'dien_vien'         => 'Chloë Grace Moretz, Jack Reynor, Gary Carr',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '60',
                'mo_ta'             => 'The Peripheral là một bộ phim viễn tưởng dựa trên tiểu thuyết của William Gibson, kể về một phụ nữ trẻ phát hiện ra một kết nối với tương lai và phải đối mặt với những mối đe dọa từ cả hai thế giới.',
                'trailer'           => 'https://www.youtube.com/embed/bRdkRQzcrrc?si=OR1PG5B8GWNE07ch',
                'link_phim'         => 'https://www.youtube.com/embed/bRdkRQzcrrc?si=OR1PG5B8GWNE07ch',
                'ngay_khoi_chieu'   => '2024-06-15',
                'ngay_ket_thuc'     => '2024-09-15',
                'trang_thai'        => 0,
                'created_at'        => '2024-06-15 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'The Gilded Age',
                'slug_phim'         => 'the-gilded-age',
                'id_the_loai'       => 6,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://daytimeconfidential.com/.image/ar_8:10%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_620/MjA4NTMxNTA3NTUwMTAyNzAx/the-gilded-age.jpg',
                'dao_dien'          => 'Michael Engler',
                'dien_vien'         => 'Christine Baranski, Cynthia Nixon, Carrie Coon',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '60',
                'mo_ta'             => 'The Gilded Age là một bộ phim lịch sử về thời kỳ Gilded Age ở Mỹ, tập trung vào cuộc sống của các gia đình giàu có và những thay đổi xã hội lớn lao trong thời kỳ này.',
                'trailer'           => 'https://www.youtube.com/embed/wKj1cMz3yfI?si=KwqVEQig9RyhG8l2',
                'link_phim'         => 'https://www.youtube.com/embed/wKj1cMz3yfI?si=KwqVEQig9RyhG8l2',
                'ngay_khoi_chieu'   => '2024-01-10',
                'ngay_ket_thuc'     => '2024-04-10',
                'trang_thai'        => 0,
                'created_at'        => '2024-01-10 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,

            ],
            [
                'ten_phim'          => 'Vikings: Valhalla',
                'slug_phim'         => 'vikings-valhalla',
                'id_the_loai'       => 6,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://www.crew-united.com/Media/Images/1481/1481596/1481596.entity.jpg',
                'dao_dien'          => 'Jeb Stuart',
                'dien_vien'         => 'Sam Corlett, Frida Gustavsson, Leo Suter',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '50',
                'mo_ta'             => 'Vikings: Valhalla là một bộ phim lịch sử tiếp nối câu chuyện của các chiến binh Viking, tập trung vào cuộc phiêu lưu của Leif Erikson, Freydis Eriksdotter và Harald Hardrada.',
                'trailer'           => 'https://www.youtube.com/embed/Yi4YnwFT7Gk?si=Oa6UjF3TsdIerimq',
                'link_phim'         => 'https://www.youtube.com/embed/Yi4YnwFT7Gk?si=Oa6UjF3TsdIerimq',
                'ngay_khoi_chieu'   => '2024-07-01',
                'ngay_ket_thuc'     => '2024-10-01',
                'trang_thai'        => 0,
                'created_at'        => '2024-07-01 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Black Doves',
                'slug_phim'         => 'black-doves',
                'id_the_loai'       => 7,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABZcMjiMQiPpwIFMW3M0oBk-JNqifRS6vtTeESi6CP34ALU0hojTQ_12xpwZ3dED_09keV-L9uE_fzW_GPYAdL6yvlhgNqHnNYImJ7_6mrXFqpZ2LpPyHlRwzd0Aep2dHzUKsDA.jpg?r=26c',
                'dao_dien'          => 'Joe Barton',
                'dien_vien'         => 'Keira Knightley, Ben Whishaw, Sarah Lancashire',
                'quoc_gia'          => 'Anh',
                'thoi_luong'        => '60',
                'mo_ta'             => 'Black Doves là một bộ phim tâm lý về một người phụ nữ có cuộc sống bí mật như một điệp viên bị đe dọa sau khi người tình của cô bị ám sát.',
                'trailer'           => 'https://www.youtube.com/embed/1R0d2jW7a-I?si=hx2KnSChw_rPmMoD',
                'link_phim'         => 'https://www.youtube.com/embed/1R0d2jW7a-I?si=hx2KnSChw_rPmMoD',
                'ngay_khoi_chieu'   => '2024-12-01',
                'ngay_ket_thuc'     => '2025-02-01',
                'trang_thai'        => 0,
                'created_at'        => '2024-12-01 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'Wizards Beyond Waverly Place',
                'slug_phim'         => 'wizards-beyond-waverly-place',
                'id_the_loai'       => 8,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://m.media-amazon.com/images/M/MV5BYzVmOWQ4ZmUtNjU4Mi00YmYzLTljMmEtZTlkM2Y5MWIxMTgyXkEyXkFqcGc@._V1_.jpg',
                'dao_dien'          => 'Todd J. Greenwald',
                'dien_vien'         => 'Selena Gomez, David Henrie, Jake T. Austin',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '45',
                'mo_ta'             => 'Wizards Beyond Waverly Place là một bộ phim giả tưởng tiếp nối câu chuyện của gia đình Russo khi họ khám phá những vùng đất mới và đối mặt với những thử thách phép thuật mới.',
                'trailer'           => 'https://www.youtube.com/embed/BtCBanGregI?si=OorMGzEsNPXxvxe8',
                'link_phim'         => 'https://www.youtube.com/embed/BtCBanGregI?si=OorMGzEsNPXxvxe8',
                'ngay_khoi_chieu'   => '2024-10-05',
                'ngay_ket_thuc'     => '2025-01-05',
                'trang_thai'        => 0,
                'created_at'        => '2024-10-05 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
            [
                'ten_phim'          => 'The Gentlemen',
                'slug_phim'         => 'the-gentlemen',
                'id_the_loai'       => 10,
                'loai_phim'         => 2,
                'hinh_anh'          => 'https://upload.wikimedia.org/wikipedia/vi/thumb/0/06/The_Gentlemen_poster.jpg/220px-The_Gentlemen_poster.jpg',
                'dao_dien'          => 'Guy Ritchie',
                'dien_vien'         => 'Theo James, Kaya Scodelario, Giancarlo Esposito',
                'quoc_gia'          => 'Mỹ',
                'thoi_luong'        => '50',
                'mo_ta'             => 'The Gentlemen là một bộ phim hành động về Eddie Halstead, người thừa kế một đế chế cần sa khổng lồ và phải đối mặt với những kẻ thù nguy hiểm trong thế giới ngầm.',
                'trailer'           => 'https://www.youtube.com/embed/2B0RpUGss2c?si=U8iuVtGIAvVTpQzN',
                'link_phim'         => 'https://www.youtube.com/embed/2B0RpUGss2c?si=U8iuVtGIAvVTpQzN',
                'ngay_khoi_chieu'   => '2024-09-17',
                'ngay_ket_thuc'     => '2024-12-17',
                'trang_thai'        => 0,
                'created_at'        => '2024-09-17 00:00:00',
                'gia_ban'           => 5000,
                'duyet_phim'        => 0,
                'luot_xem'         => 0,
            ],
        ]);
    }
}
